[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "moodscope-backend"

[services.source]
repo = "https://github.com/YOUR_USERNAME/moodscope-backend"

[services.variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"
